{% set version = "1.3.5" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/v{{ version }}.tar.gz
  sha256: 4f582e1c5ced841a052d547ae8e28ab11e1cac0e912c97235b0bb654b3b4c47b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - poetry
    - cython
    - numpy
  run:
    - python
    - six
    - numpy
    - setuptools

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
