{% set version = "1.2.5" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/v{{ version }}.tar.gz
  sha256: ef04542bb180d1ac24ca909a5c44f6d8d0c67d38b4ad44ff096e50c85bddfbc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
    - poetry
  run:
    - python >=3.5
    - six
    - numpy
    - setuptools

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
