{% set version = "1.0.1" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/v{{ version }}.tar.gz
  sha256: 1b806d9644d416dfcdea1b6284b072f81f649251177b372a2f23500c28573876

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
    - poetry
  run:
    - python >=3.5
    - six
    - numpy
    - setuptools

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
