{% set version = "0.1.13" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/v{{ version }}.tar.gz
  sha256: 32d7227b511dbc028be70f3c5766331a8dd5a6b55a3a6aaa94a307e24ef18aad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
    - poetry
  run:
    - python >=3.5
    - six
    - numpy

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
