{% set version = "0.3.0" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/v{{ version }}.tar.gz
  sha256: 99cfbea85253e77002fd03b8d8aae2c051908f899bad6ecb9e3e7f7f9dec1f93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
    - poetry
  run:
    - python >=3.5
    - six
    - numpy
    - setuptools

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
