{% set version = "1.3.8" %}

package:
  name: numpoly
  version: {{ version }}

source:
  url: https://github.com/jonathf/numpoly/archive/{{ version }}.tar.gz
  sha256: 5f8358a4269ff2a714081ceb8d2e7673c802256afd44e98c0735f73ca69890fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - poetry
    - cython
  run:
    - python
    - six
    - numpy
    - setuptools

test:
  imports:
    - numpoly

about:
  home: https://github.com/jonathf/numpoly
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Numpy compatible polynomial representation

extra:
  recipe-maintainers:
    - jschueller
